### ISSUE TITLE
Support any thenable object

### ISSUE THREAD

**Issue by joshdifabio** [clue/php-block-react#18]
It would be helpful for this library to support non-React promises.

`if (method_exists($pr, 'then')) ...`

**Comment by clue** [comment]
Thanks for your feature request @joshdifabio :+1: 

I understand where you're coming from and I see some use in this, but should this really be part of this lib?

This library relies on react/event-loop anyway, so it makes sense to rely on react/promise as well.

As an alternative, we may want to document usage with foreign promise providers. As of v2.4.0 react/promise supports wrapping foreign promises like this:

```php
$foreignPromise = operationWithForeignPromise();
$reactPromise = Promise\resolve($foreignPromise);

$result = Block\await($reactPromise, $loop);
```

**Comment by joshdifabio** [comment]
Yeah, the changes in react/promise 2.4 make this pretty redundant. I don't have any strong feelings either way so feel free to close this issue.

**Comment by clue** [comment]
Thanks for reporting back! I'll close this for now, but I'm willing to reconsider this once a need arises :+1:
