### ISSUE TITLE
Breaking main React loop

### ISSUE THREAD

**Issue by maciejmrozinski** [clue/php-block-react#20]
Hi,

I have a following use case:

I'm using [php-pm](https://github.com/php-pm/php-pm) for request-response flow with [psr7-adapter](https://github.com/php-pm/php-pm-psr7). So, my main class (application) is invoked with PSR7 request and response objects as any other middleware. An expected return value for middleware must be an instance of PSR7-Response. Since I'm using React HTTP client to call some APIs in my app I'm forced to use `php-block-react` so the PSR7-Response will be returned after all promises are done and data from APIs will be placed in PSR7-Response mentioned above. In simple words:

1. I receive PSR7-Request
2. I run few promises to call external APIs
3. I set `await` function to wait for all promises and block returning empty PSR7-Response
4. I parse promises response and fill my PSR7-Response with proper data
5. I return ready PSR7-Response object

I hope all here is clear and now my issue ;)

`await` function calls `$loop->run()` internally for obvious reasons. After all conditions for `await` functions are meet (promises fulfilled), the `$loop->stop()` is called (I also understand why it must be done like that). So, after `await` function my main React loop is turned `off` and my whole application is shutted down, since there is now way to turn React loop `on` again. Below I post simple example (different code, but the same principle):

```json
{
  "name": "vendor_name/package_name",
  "description": "description_text",
  "minimum-stability": "stable",
  "license": "proprietary",
  "authors": [
    {
      "name": "author's name",
      "email": "email@example.com"
    }
  ],
  "require": {
    "clue/block-react": "^1.1.0"
  }
}
```

```php
<?php

require_once 'vendor/autoload.php';

$loop = \React\EventLoop\Factory::create();

// postpone await, so main loop can be started
$loop->addTimer(0.5, function () use ($loop) {
    $promise = \React\Promise\Timer\resolve(6, $loop);
    $promise = $promise->then(function() {
        echo 'timer promise done' . PHP_EOL;
    });

    echo 'await loop start' . PHP_EOL;
    \Clue\React\Block\await($promise, $loop);
    echo 'await loop end' . PHP_EOL;
});

$loop->addPeriodicTimer(1, function() {
    echo 'test' . time() . PHP_EOL;
});

echo 'main loop start' . PHP_EOL;
$loop->run();
echo 'main loop end' . PHP_EOL;
```

I resolved this by creating second, internal React loop to handle every new request. By this I gain possibility to shutdown only internal loop (not the whole app), but in the time of processing request (and all external API calls), my main React loop is blocked, so obviously not a great, final solution :/

Any help is appreciated, maybe I'm doing something totally wrong here :/ Maybe I'm doing all right, this library is also totally correct, but the problem lies in absence of `$loop->resume()` function which will set `$loop->running = true` as `stop()` method sets it to `false`.

**Comment by clue** [comment]
Thanks for filing this interesting ticket, but I'm really not sure there's much we can here, unfortunately.

As a rule of thumb, mixing async and sync code is never a good idea and should generally be avoided in the first place.

In this particular case, I would probably suggest keeping a second, inner loop which should indeed resolve most of the issues you're seeing. However, this will in fact block the outer loop and this is not something that can easily be avoided with your current middleware design.

In the longer run, I would suggest keeping an eye on https://github.com/reactphp/http/issues/28 where we will *very likely* promote a sightly modified middleware approach where each middleware can actually return a promise which eventually resolves to a response.

I hope this helps :+1:

**Comment by maciejmrozinski** [comment]
> In the longer run, I would suggest keeping an eye on reactphp/http#28 where we will very likely promote a sightly modified middleware approach where each middleware can actually return a promise which eventually resolves to a response.

Yup, this actually should help. Thx

**Comment by Tatikoma** [comment]
I got same issue.

Why not just resume loop, after await finished?

```php
// functions.php
function await(PromiseInterface $promise, LoopInterface $loop, $timeout = null)
{
// ...
    while ($wait) {
        $loop->run();
    }

    if($loop instanceof \React\EventLoop\StreamSelectLoop) {
        $reflection = new \ReflectionClass($loop);
        $property = $reflection->getProperty('running');
        $property->setAccessible(true);
        $property->setValue($loop, true);
    }
// ...
```

**Comment by clue** [comment]
@Tatikoma This may or may not work in your particular setup, but there's really no way to support this on a general level because the event loop assumes control over your program flow.

See also my above comment, but as a rule of thumb, mixing async and sync code is never a good idea and should generally be avoided in the first place.

**Comment by Tatikoma** [comment]
@clue Thanks. I understood that (mixing async and sync code is never a good idea) after few hours debugging. I'll nevermore mix sync & async code.

**Comment by BitBargain** [comment]
All of my code is async and I do not mean to block the whole process. I wanted to add this loopy waiting inside a promise that has a resolver and that resolver could run when this waiting has finished. It's basically about running a bunch of jobs (querying a server in sequence) and waiting for the last one to finish.

I've solved it by using a resolver that calls the original function on every partial resolution, but that builds a stack AFAIK, so it's not optimal. It would have been so much cleaner to introduce a local blocking inside a for, a wait() that worked similar to select() which allowed for other tasks in the loop to run asynchronously and once they were done, the wait() would get a signal from the loop controller and then that local code could proceed from there and finally resolve the main promise it was in.

Does this make sense?

**Comment by clue** [comment]
@BitBargain Your suggested solution sounds like a perfect replacement :+1:

Don't worry about building up a stack as your promise resolution handlers will usually be called from different loop ticks and the stack will reset :+1:
