### ISSUE TITLE
Problem with ExtEventLoop (event)

### ISSUE THREAD

**Issue by alexpts** [clue/php-block-react#33]
```php
$promise = new Promise(function (callable $resolve) use ($path) {
        $this->loop->addTimer(2, function () use ($resolve) {
        echo "resolver \n";
        $resolve('async done');
});

$result = await($promise, $loop)
```

Warning: EventBase::loop(): event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once. in /Users/alex/www/alex/php-crop-service/vendor/react/event-loop/src/ExtEventLoop.php on line 204

It dont work on ExtEventLoop, only StreamSelectLoop.

Do you have idea how fix it?

**Comment by alexpts** [comment]
@clue

**Comment by alexpts** [comment]
up

**Comment by markkimsal** [comment]
@alexpts what versions of everything are you using?  I just started from a clean directory:

```
composer require clue/block-react:^1.2
tar -zxvf ~/Downloads/event-2.3.0.tgz
cd event-2.3.0
phpize; ./configure; make; sudo make install;
```

```
php -d extension=event.so  ./start.php 
using loop: React\EventLoop\ExtEventLoop
starting timer
resolver 
```

```
php  ./start.php                                                                                                      
using loop: React\EventLoop\StreamSelectLoop                                       
starting timer                           
resolver                                 
```

```
php -v
PHP 7.2.3-1+ubuntu17.10.1+deb.sury.org+1 (cli) (built: Mar  6 2018 11:19:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3-1+ubuntu17.10.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

```
cat start.php
<?php
include('vendor/autoload.php');

$loop = React\EventLoop\Factory::create();
echo "using loop: ". get_class($loop)."\n";

$promise = new \React\Promise\Promise(function (callable $resolve) use ($loop) {
    echo "starting timer\n";
    $loop->addTimer(2, function () use ($resolve) {
        echo "resolver \n";
        $resolve('async done');
    });
});

$result = \Clue\React\Block\await($promise, $loop);
```

**Comment by markkimsal** [comment]
You can use 2 loops if you want to `await()` one promise inside another loop you can use 2 loops
```
<?php
include('vendor/autoload.php');

$loop1 = React\EventLoop\Factory::create();
$loop2 = React\EventLoop\Factory::create();
echo "using loop1: ". get_class($loop1)."\n";
echo "using loop2: ". get_class($loop2)."\n";


$loop1->addPeriodicTimer(2, function () use($loop2){
    $promise = new \React\Promise\Promise(function (callable $resolve) use ($loop2) {
        echo "starting timer\n";
        $loop2->addTimer(2, function () use ($resolve) {
            echo "timer done \n";
            echo "loop 2 stopped \n";                                                                                                                                 
            $resolve('async done');
        });
    });

    $result = \Clue\React\Block\await($promise, $loop2);
});

$loop1->addPeriodicTimer(1, function () use($loop2){
    echo "I am loop 1\n";
});
$loop1->run();
```

But `await()` will hang your outer loop, it is blocking after all.

**Comment by alexpts** [comment]
Thanks! I used 1 loop for all.
It help :)

May be need add more example to readme.md for this case.

**Comment by clue** [comment]
@markkimsal Thank you very much for helping with analyzing and fixing this problem for @alexpts!

@alexpts Happy to hear this is resolved for you! I'm not sure I fully understand the problem you're seeing and/or your particular use-case, but if you feel like filing a PR to improve the documentation, I'm happy to get this in! :shipit:

**Comment by alexpts** [comment]
@clue I updated example on first topic and add demo for my case - https://github.com/alexpts/php-react-await-problem

I used one loop for http server and await function.

**Comment by clue** [comment]
Using blocking functions in a truly async application should always be avoided.

Instead of:

```php
$server = new \React\Http\Server(function (ServerRequestInterface $request) use ($loop) {
    $promise = new Promise(function (callable $resolve) use ($loop) {
        $loop->addTimer(10, function () use ($resolve) {
            $resolve('async done');
        });
    });
    $result = await($promise, $loop);
    return new Response(
        200,
        ['Content-Type' => 'text/plain'],
        $result
    );
});
```

Use something like this instead:

```php
$server = new \React\Http\Server(function (ServerRequestInterface $request) use ($loop) {
    return new Promise(function (callable $resolve) use ($loop) {
        $loop->addTimer(10, function () use ($resolve) {
            $resolve(new Response(
                200,
                ['Content-Type' => 'text/plain'],
                'async done'
            ));
        });
    });
});
```

To further simplify this logic, you may as well use https://github.com/reactphp/promise-timer#resolve.

I hope this helps :+1:

**Comment by alexpts** [comment]
It possible only for reactPhp middleware, but not PSR-15, it simple demo.
In real I use PSR15 middleware. It must return only ResponseInterface and cant return Promise object:

Real example:
```php
class FetchImageUrl implements MiddlewareInterface
{
    public function process(ServerRequestInterface $request, RequestHandlerInterface $next): ResponseInterface
    {
        $promise = $this->someAsyncMethod($request); // I want promise resolve and handle other http request until wait async method
        $request = $request->withAttribute('some', await($promise, $loop));

        return $next->handle($request);
    }

}

**Comment by alexpts** [comment]
I think about Promise middleware adapter.

It good work on nodejs platform and i find similar for php.
But PHP not have async function as js.

```js
var express = require('express');
var app = express();

app.get('/', async function(req, res) {
   let result = await asyncFetch('url'); // wait not blocking loop
   res.send(result);
});
```

**Comment by clue** [comment]
I agree that having some language primitives for this would a awesome. Note however that this is essentially just syntactic sugar for a callable function that returns a promise.

This means that even if PHP were to support `async`/`await` keywords, this would not be compatible with PSR-15. But having these as language constructs certainly makes it more reasonable to expect a future PSR-X which considers non-blocking to be a core feature :+1: :tada:

**Comment by markkimsal** [comment]
The c-extension libevent is not reentrant.  It doesn't like being called from inside itself.  The `await()` function is being called inside an async function, which means it's some lambda or callback attached to the c-extension libevent.  This works for StreamSelectLoop because it's all userland PHP, only calling stream_select() which returns right away.

So, you're "inside"  `$this->loop->run($flags);` and you want to go "back inside" with `await()`.

`await()` simply burns cpu cycles (why not, that's blocking right?) until the promise is complete.  But, if the promise is a lambda attached to the c-extension, burning cycles in userland will never give that extension time to trigger.  So, it's really an impossible situation to block from async code with a non-reentrant event extension.

**Comment by alexpts** [comment]
Maybe then a name `wait` is more appropriate instead `await` for function?
